apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: usermgmt-webapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: usermgmt-webapp-service 
            port:
              number: 80