apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premimum-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain #default delete, recommended is retain. 
volumeBindingMode: WaitForFirstConsumer #Default is immediate. 
allowVolumeExpansion: true
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
